version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=python_api
      - SECRET_KEY=976e1f07497d4b018e912e464c4af0613116474336c57975f074b850c8e6ce3f
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=python_api

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: